Add ArangoDB snapshot store
prooph/arangodb-snapshot-store pull request #1
Opened 2016-12-11 11:36 UTC by sandrokeil

2016-12-11 14:30 UTC, prolic reviewed
looks great!

2016-12-11 14:30 UTC, prolic commented on LICENSE
> +Copyright (c) 2014-2015, prooph software GmbH
2016-2016

2016-12-11 14:30 UTC, prolic commented on LICENSE
> +Copyright (c) 2015-2016, Sascha-Oliver Prolic
2016-2016

2016-12-11 14:30 UTC, prolic commented on README.md
> +- ArangoDB >= 3.0
seems like: 3.2.11

or you add 3.0 also to the build matrix

2016-12-11 14:30 UTC, prolic commented on src/ArangoDBSnapshotStore.php
> +        if ($aggregateRoot instanceof \JsonSerializable) {
oh that's nice, can you create PR and add that for mongodb- & pdo-snapshot-store, too?

2016-12-11 14:35 UTC, prolic commented
I added coveralls.
Having problems with packagist login right now (@codeliner?)
Travis-CI has some problems currenty, prooph is missing from my organizations (but it's in github).

2016-12-11 15:51 UTC, sandrokeil commented on src/ArangoDBSnapshotStore.php
> +        if ($aggregateRoot instanceof \JsonSerializable) {
Will do :-)

2016-12-11 15:52 UTC, sandrokeil commented on README.md
> +- ArangoDB >= 3.0
Will do

2016-12-11 15:52 UTC, sandrokeil commented on LICENSE
> +Copyright (c) 2015-2016, Sascha-Oliver Prolic
Alright

2016-12-11 15:52 UTC, sandrokeil commented on LICENSE
> +Copyright (c) 2014-2015, prooph software GmbH
Alright

2016-12-11 17:46 UTC, prolic commented
Packagist is created:
https://packagist.org/packages/prooph/arangodb-snapshot-store

Travis-CI, too.

2016-12-11 17:47 UTC, prolic commented
I added composer.json manually, the PR needs to be rebased.

2016-12-11 20:47 UTC, sandrokeil commented on src/ArangoDBSnapshotStore.php
> +                : unserialize($result->aggregate_root, ['allowed_classes' => [$aggregateType->toString()]]),
@prolic If we use `JsonSerializable` we need a mechanism to create the aggregate root from an `array`. Any suggestions? Should we use an own interface where the user have to implement `fromArray` too or do I miss something? I've added an extra field in `save` to mark if it was saved as `json`.

We should also add the `allowed_classes` option to `unserialize` for security reasons (PHP Object Injection Vulnerability). Should we add other classes like `\Prooph\EventSourcing\AggregateRoot` too? 

/cc @codeliner

2016-12-11 20:55 UTC, prolic commented on src/ArangoDBSnapshotStore.php
> +                : unserialize($result->aggregate_root, ['allowed_classes' => [$aggregateType->toString()]]),
Perhaps we can add another class:

`JsonSerializableAggregateRoot extends AggregateRoot`

:+1: for `allowed_classes` - but only aggregate type, not the base class AggregateRoot

2016-12-11 21:13 UTC, prolic commented on src/ArangoDBSnapshotStore.php
> +                : unserialize($result->aggregate_root, ['allowed_classes' => [$aggregateType->toString()]]),
On the other hand I see it a little dangerous to have another public contructor (`fromArray`) which could be used to create an aggregate root in invalid state.

2016-12-11 21:15 UTC, sandrokeil commented
This error makes no sense to me, because I don't see the failure. :thinking: 

```
1) ProophTest\ArangoDB\SnapshotStore\ArangoDBSnapshotStoreTest::it_saves_and_reads
Class __PHP_Incomplete_Class has no unserializer
```

2016-12-11 21:45 UTC, sandrokeil commented on src/ArangoDBSnapshotStore.php
> +                : unserialize($result->aggregate_root, ['allowed_classes' => [$aggregateType->toString()]]),
That's true, we have two problems, `allowed_classes` don't work (see below) and we can not create an aggregate root from `JsonSerializable`.

2016-12-12 06:06 UTC, prolic commented
@sandrokeil You're right. We would need to add all classes involved in the aggregate root, which is completely unknown to the snapshot-store. So we have to remove it. For security we could only encrypt / decrypt the serialized string, so nobody is able to manipulate the data, but I think this is too much and costs also performance. So let's remove allowed_classes.

2016-12-12 06:08 UTC, prolic commented
Second: I think we should also remove JsonSerializable, this would either require all uses value objects to also implement this or having a complex serialization method in the aggregate root PLUS it's dangerous to have a public static fromArray-method, as it can be used to create aggregate roots in invalid state.

2016-12-12 21:46 UTC, sandrokeil commented
@prolic I've updated the code. Here is a slide about [PHP Object Injection](https://2016.php.ruhr/wp-content/uploads/2016/12/rips_php.ruhr_.pdf) (Chapter 5).

This is strange, all tests are green. :D Locally I get an error in `it_saves_and_reads` that the objects are not equal. Must be a PHP in Docker Bug or mabye a PHPUnit Bug.

2016-12-12 21:59 UTC, sandrokeil commented
Any ideas why the build times out?

2016-12-15 05:33 UTC, prolic commented on src/ArangoDBSnapshotStore.php
> +    FILTER s._key == @aggregate_id && s.aggregate_type == @aggregate_type
Filter on aggregate id should be enough, because we use uuid, they are unique.

2016-12-16 17:21 UTC, sandrokeil commented
@prolic I've removed the `aggregate_type` from query, but it was stolen from [PDO Snapshotter](https://github.com/prooph/pdo-snapshot-store/blob/master/src/PDOSnapshotStore.php#L54). So we should it change too.

2016-12-16 18:02 UTC, prolic commented
build still failing... I'll install arangodb on my machine and check...

2016-12-16 18:19 UTC, sandrokeil commented
Yes, Travis can not shutdown. Still trying some stuff to solve this.

2016-12-16 18:32 UTC, prolic commented
@sandrokeil a suggestion: check other github repositories, where arangodb is tested (maybe event arangodb build itself) - perhaps there you'll find something.

Testing locally - all runs, but I got a lot of debug output. Seems like you did this within TestUtil.php - for travis testing I guess?

2016-12-19 22:27 UTC, sandrokeil commented
@prolic Yes, the debug logs are for the travis issue. I will remove it wen I solved the problem.

2016-12-19 22:46 UTC, sandrokeil commented
@prolic Ready to merge :tada:

2016-12-20 18:33 UTC, prolic requested changes

2016-12-20 18:33 UTC, prolic commented on README.md
> +- ArangoDB >= 3.0
Add 3.2 to travis

2016-12-20 18:33 UTC, prolic commented on README.md
> +- File issues at [https://github.com/prooph/event-store/issues](https://github.com/prooph/event-store/issues).
Arangodb, not event-store

2016-12-20 18:33 UTC, prolic commented on tests/TestUtil.php
> +//            ConnectionOptions::OPTION_TRACE => new TraceError(),
Remove line

2016-12-21 16:27 UTC, sandrokeil commented
@prolic Good catch, but there exists no ArangoDB 3.2 version.

2016-12-21 16:37 UTC, merged